// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("https://artisan-ai-a5f011e35d03.herokuapp.com/login/?next=/post/97/")
    await driver.manage().window().setRect({ width: 1366, height: 768 })
    await driver.findElement(By.id("username_or_email")).click()
    await driver.findElement(By.id("username_or_email")).sendKeys("userbeginner")
    await driver.findElement(By.id("password")).sendKeys("Abc_1234")
    await driver.findElement(By.css(".project-btn-secondary")).click()
  })
})
