// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("https://rahulshettyacademy.com/angularpractice/")
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("John")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("email@email.com")
    await driver.findElement(By.css(".form-group:nth-child(3)")).click()
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("password")
    await driver.findElement(By.css(".ng-dirty > .form-check")).click()
    await driver.findElement(By.id("exampleCheck1")).click()
    await driver.findElement(By.id("exampleFormControlSelect1")).click()
    await driver.findElement(By.css("option:nth-child(1)")).click()
    await driver.findElement(By.css(".form-check:nth-child(2)")).click()
    await driver.findElement(By.id("inlineRadio1")).click()
    await driver.findElement(By.name("bday")).click()
    await driver.findElement(By.name("bday")).click()
    await driver.findElement(By.name("bday")).sendKeys("0001-01-01")
    await driver.findElement(By.name("bday")).sendKeys("0019-01-01")
    await driver.findElement(By.name("bday")).sendKeys("0199-01-01")
    await driver.findElement(By.name("bday")).sendKeys("1991-01-01")
    await driver.findElement(By.css(".ng-dirty:nth-child(3)")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})
