// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login', async function() {
    await driver.get("https://login.microsoftonline.com/9082fa50-02ab-43ec-adcb-5e9ab5919981/oauth2/authorize?client_id=00000003-0000-0ff1-ce00-000000000000&response_mode=form_post&response_type=code+id_token&resource=00000003-0000-0ff1-ce00-000000000000&scope=openid&nonce=FD71C65B62CA4E42C0421C8234F6268657A21B7CD1E39DFD-983E6A9A6728537DD5A3D85490379FA45848E9A18A3788360B53F9271BC0BCBD&redirect_uri=https%3a%2f%2fmgenesis.sharepoint.com%2f_forms%2fdefault.aspx&state=OD0w&claims=%7b%22id_token%22%3a%7b%22xms_cc%22%3a%7b%22values%22%3a%5b%22CP1%22%5d%7d%7d%7d&wsucxt=1&cobrandid=11bd8083-87e0-41b5-bb78-0bc43c8a8e8a&client-request-id=11240ba1-10ff-2000-fc5a-e7c05d0050c0&sso_nonce=AwABAAEAAAACAOz_BQD0_1SkC3Fs6SlTDqWszZXpBVrYVN-pSncC6snZla9Qr-h08Xk8NZMF6TgKLrF1cS1JolaXoDrUekn5MCL1EO64EDYgAA&mscrid=11240ba1-10ff-2000-fc5a-e7c05d0050c0")
    await driver.manage().window().setRect(1936, 1048)
    await driver.findElement(By.id("otherTileText")).click()
    await driver.findElement(By.id("i0116")).sendKeys("itsddev.intern2@mgenesis.com")
    await driver.findElement(By.id("i0118")).sendKeys("Ruthintern05*")
    await driver.findElement(By.id("i0116")).click()
    await driver.findElement(By.id("i0116")).click()
    await driver.findElement(By.css(".pagination-view > div")).click()
    await driver.findElement(By.id("idSIButton9")).click()
    {
      const element = await driver.findElement(By.id("idSIButton9"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("i0118")).sendKeys("Ruthintern05*")
    await driver.findElement(By.id("i0118")).click()
    await driver.findElement(By.id("i0118")).click()
    {
      const element = await driver.findElement(By.id("i0118"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("i0118")).sendKeys("Ruthintern05*")
    await driver.findElement(By.id("i0118")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".row:nth-child(1) .text-left")).click()
    await driver.findElement(By.id("idChkBx_SAOTCC_TD")).click()
    await driver.findElement(By.id("idTxtBx_SAOTCC_OTC")).click()
    await driver.findElement(By.id("idTxtBx_SAOTCC_OTC")).sendKeys("398404")
    await driver.findElement(By.id("idSubmit_SAOTCC_Continue")).click()
    await driver.findElement(By.id("skipMfaRegistrationLink")).click()
    await driver.findElement(By.css("span")).click()
    await driver.findElement(By.id("idSIButton9")).click()
    {
      const element = await driver.findElement(By.id("idSIButton9"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Edit")).click()
  })
})
