// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('edit', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('edit', async function() {
    await driver.get("https://mgenesis.sharepoint.com/sites/DigiCash/SitePages/FormType.aspx?formType=IBERF2024000005")
    await driver.manage().window().setRect({ width: 1167, height: 775 })
    await driver.findElement(By.css(".Form")).click()
    await driver.findElement(By.id("prjName")).click()
    await driver.findElement(By.id("prjName")).sendKeys("Project Edit")
    await driver.findElement(By.id("needDate")).click()
    await driver.findElement(By.id("needDate")).sendKeys("2024-02-14")
    await driver.findElement(By.id("prebidDate")).click()
    await driver.findElement(By.id("prebidDate")).sendKeys("2024-02-16")
    await driver.findElement(By.id("bidDate")).click()
    await driver.findElement(By.id("bidDate")).sendKeys("2024-02-20")
    await driver.findElement(By.id("rqstr")).click()
    {
      const element = await driver.findElement(By.id("prjAmt"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("rqstr")).sendKeys("Itsd Dev Intern 1")
    await driver.findElement(By.id("client")).click()
    await driver.findElement(By.id("client")).sendKeys("Microgenesis Business Systems")
    await driver.findElement(By.id("select")).click()
    {
      const dropdown = await driver.findElement(By.id("select"))
      await dropdown.findElement(By.xpath("//option[. = 'Social Media']")).click()
    }
    await driver.findElement(By.css("#select > option:nth-child(6)")).click()
    await driver.findElement(By.id("prjAmt")).click()
    await driver.findElement(By.id("prjAmt")).sendKeys("20000")
    await driver.findElement(By.id("gpa")).click()
    await driver.findElement(By.id("gpa")).sendKeys("29999")
    await driver.findElement(By.id("gpa")).sendKeys("29998")
    await driver.findElement(By.id("bdgtAmt2")).click()
    await driver.findElement(By.id("bdgtAmt2")).sendKeys("5000")
    await driver.findElement(By.id("bdgtAmt3")).click()
    await driver.findElement(By.id("bdgtAmt3")).sendKeys("5000")
    await driver.findElement(By.id("bdgtAmt1")).click()
    await driver.findElement(By.id("bdgtAmt1")).sendKeys("10000")
    await driver.findElement(By.id("bdgtAmt3")).click()
    await driver.findElement(By.id("bdgtAmt3")).sendKeys("500")
    await driver.findElement(By.id("addRowBtn")).click()
    {
      const element = await driver.findElement(By.id("addRowBtn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("partSelect4")).click()
    {
      const dropdown = await driver.findElement(By.id("partSelect4"))
      await dropdown.findElement(By.xpath("//option[. = 'Transportation']")).click()
    }
    await driver.findElement(By.css("#partSelect4 > option:nth-child(5)")).click()
    await driver.findElement(By.id("bdgtAmt4")).click()
    await driver.findElement(By.id("bdgtAmt4")).sendKeys("500")
    await driver.findElement(By.css("#exp1 .fa")).click()
    await driver.findElement(By.id("bdgtAmt2")).click()
    await driver.findElement(By.id("bdgtAmt3")).click()
    await driver.findElement(By.id("bdgtAmt3")).sendKeys("1500")
    await driver.findElement(By.id("bdgtAmt4")).click()
    await driver.findElement(By.id("bdgtAmt4")).click()
    await driver.findElement(By.id("bdgtAmt4")).sendKeys("2500")
    await driver.findElement(By.css(".col-md-9")).click()
    await driver.findElement(By.id("cancelBtn")).click()
    await driver.findElement(By.css("#down3 > .fas")).click()
    {
      const element = await driver.findElement(By.css("#O365_MainLink_Help > .o365cs-base"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
