// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('editprofile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('editprofile', async function() {
    await driver.get("https://artisan-ai-a5f011e35d03.herokuapp.com/post/97/")
    await driver.manage().window().setRect({ width: 1366, height: 768 })
    await driver.findElement(By.id("usericon")).click()
    await driver.findElement(By.css(".show > li:nth-child(1) .dropdown-item")).click()
    await driver.findElement(By.css(".profile-btn-primary")).click()
    await driver.findElement(By.id("profileThemeSelect")).click()
    {
      const dropdown = await driver.findElement(By.id("profileThemeSelect"))
      await dropdown.findElement(By.xpath("//option[. = '🧡 orange']")).click()
    }
    await driver.findElement(By.css("#profileThemeSelect > option:nth-child(3)")).click()
    await driver.findElement(By.id("postname")).click()
    await driver.findElement(By.id("postname")).sendKeys("hj")
    await driver.findElement(By.id("postdescription")).click()
    await driver.findElement(By.id("postdescription")).sendKeys("hi, i\'m hyunjin!")
    await driver.findElement(By.id("difficultySelect")).click()
    {
      const dropdown = await driver.findElement(By.id("difficultySelect"))
      await dropdown.findElement(By.xpath("//option[. = 'beginner']")).click()
    }
    await driver.findElement(By.css("#difficultySelect > option:nth-child(1)")).click()
    await driver.findElement(By.css(".select-btn-preferences")).click()
    await driver.findElement(By.css("label:nth-child(8)")).click()
    await driver.findElement(By.css("label:nth-child(6)")).click()
    await driver.findElement(By.css("label:nth-child(2)")).click()
    await driver.findElement(By.css("label:nth-child(22)")).click()
    await driver.findElement(By.id("tagsSelect")).click()
    await driver.findElement(By.css(".project-btn-primary")).click()
  })
})
