// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test', async function() {
    await driver.get("https://mgenesis.sharepoint.com/sites/DigiCash/SitePages/LandingPage.aspx")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.css("#prj4 .zmdi")).click()
    await driver.findElement(By.linkText("Edit")).click()
    await driver.findElement(By.id("saveBtn")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to save as draft?")
    await driver.switchTo().alert().accept()
    assert(await driver.switchTo().alert().getText() == "The form has been successfully Saved")
    {
      const element = await driver.findElement(By.css(".U6Cnfo0RjXJ8UEwXhZV8mQ\\=\\="))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".U6Cnfo0RjXJ8UEwXhZV8mQ\\=\\="))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("#prj4 .dropdown > .btn")).click()
    await driver.findElement(By.linkText("Edit")).click()
    await driver.findElement(By.id("saveBtn")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to save as draft?")
    await driver.switchTo().alert().accept()
    assert(await driver.switchTo().alert().getText() == "The form has been successfully Saved")
  })
})
